Paginaion bullet
arshia11d/lit-slider pull request #4
Opened 2022-02-04 13:36 UTC by kochizufan

Fix pagination not showing error ( #2 ):

:styles.min.css.ts

 - .swiper-pagination{position:absolute;text-align:center;transition:.3s opacity;transform:translate3d(0,0,0);z-index:10}
+ .swiper-pagination{position:absolute;text-align:center;transition:.3s opacity;transform:translate3d(0,0,0);z-index:10;bottom:0;left:0;right:0}

- .swiper-pagination-bullet{width:8px;height:8px;display:inline-block;border-radius:100%;background:var(--swiper-navigation-color);opacity:.2}
+ .swiper-pagination-bullet{width:8px;height:8px;margin:2px;display:inline-block;border-radius:100%;background:var(--swiper-navigation-color);opacity:.2}

2022-02-11 12:49 UTC, arshia11d requested changes

2022-02-11 12:49 UTC, arshia11d commented on src/Slider.ts
> +			} : false,
Let's rebase this branch as I have merged your previous branch which included this.

2022-02-11 12:49 UTC, arshia11d commented on demo/Demo.ts
> +					--lit-slider-navigation-color: white;
Well, this does not have any effect as `--lit-slider-navigation-color` is not defined.

Is the idea here to have css properties starting with `--lit-slider` alongside with i.e. instead of Swiper's build-in `--swiper` properties? It might be a good idea, but let's have it separately in another issue/PR!

2022-02-11 13:15 UTC, arshia11d requested changes

2022-02-11 13:15 UTC, arshia11d commented on demo/Demo.ts
> +					--lit-slider-navigation-color: white;
Let's have this as the default value for the `--lit-slider-navigation-color` css property. See my comment in `Slider.ts`

2022-02-11 13:15 UTC, arshia11d commented on demo/Demo.ts
> +					--lit-slider-navigation-color: white;
If the intention here is to have a default value for `--lit-slider-navigation-color`, let's have it in `Slider.ts` like so:
```css
--swiper-navigation-color: var(--lit-slider-navigation-color, white);
```

I think the more important question is why Swiper's default values are not applied properly, becaust this could happen for many css properties in the future.

2022-02-13 14:45 UTC, kochizufan commented on demo/Demo.ts
> +					--lit-slider-navigation-color: white;
Is this OK?

2022-02-13 21:28 UTC, merged